Implemented Add ships function
Pravallika2812/Battleships pull request #4
Opened 2021-09-26 06:03 UTC by Pravallika2812

2021-09-27 11:00 UTC, Pragya28 requested changes

2021-09-27 14:06 UTC, Pravallika2812 commented on battleship.py
> +    board=grid
Modified the Code

2021-09-28 08:47 UTC, Pragya28 reviewed
Good work @Pravallika2812.

2021-10-06 05:39 UTC, Pragya28 approved these changes

2021-10-06 05:39 UTC, merged